#! /bin/bash

git add ./include/v8.h
git add ./include/v8-debug.h
git add ./src/fast-codegen.h
git add ./src/cached-powers.h
git add ./src/math.js
git add ./src/runtime.cc
git add ./src/token.h
git add ./src/ic-inl.h
git add ./src/log-utils.h
git add ./src/parser.h
git add ./src/allocation.h
git add ./src/liveedit-debugger.js
git add ./src/func-name-inferrer.cc
git add ./src/log-inl.h
git add ./src/messages.h
git add ./src/debug-debugger.js
git add ./src/data-flow.h
git add ./src/cpu-profiler.cc
git add ./src/fast-dtoa.h
git add ./src/ic.cc
git add ./src/third_party/dtoa/COPYING
git add ./src/third_party/dtoa/dtoa.c
git add ./src/third_party/valgrind/valgrind.h
git add ./src/v8.cc
git add ./src/heap-profiler.h
git add ./src/circular-queue-inl.h
git add ./src/d8.cc
git add ./src/spaces-inl.h
git add ./src/code-stubs.cc
git add ./src/bootstrapper.h
git add ./src/ast.cc
git add ./src/globals.h
git add ./src/version.h
git add ./src/bootstrapper.cc
git add ./src/property.h
git add ./src/jump-target-inl.h
git add ./src/snapshot-empty.cc
git add ./src/splay-tree-inl.h
git add ./src/compiler.h
git add ./src/platform-win32.cc
git add ./src/cpu-profiler-inl.h
git add ./src/heap-inl.h
git add ./src/platform-openbsd.cc
git add ./src/zone.h
git add ./src/liveedit.cc
git add ./src/d8-readline.cc
git add ./src/flags.cc
git add ./src/register-allocator.cc
git add ./src/jsregexp.h
git add ./src/prettyprinter.h
git add ./src/v8-counters.cc
git add ./src/objects.cc
git add ./src/liveedit.h
git add ./src/regexp-stack.cc
git add ./src/ast.h
git add ./src/frames.cc
git add ./src/top.h
git add ./src/stub-cache.cc
git add ./src/profile-generator.h
git add ./src/runtime.h
git add ./src/scopeinfo.h
git add ./src/dateparser-inl.h
git add ./src/top.cc
git add ./src/d8.h
git add ./src/v8.h
git add ./src/frame-element.h
git add ./src/number-info.h
git add ./src/regexp-macro-assembler.h
git add ./src/jump-target.cc
git add ./src/counters.cc
git add ./src/scanner.h
git add ./src/accessors.cc
git add ./src/debug-agent.h
git add ./src/full-codegen.h
git add ./src/serialize.cc
git add ./src/runtime.js
git add ./src/cpu.h
git add ./src/double.h
git add ./src/checks.h
git add ./src/register-allocator.h
git add ./src/mark-compact.h
git add ./src/regexp-macro-assembler-irregexp.h
git add ./src/oprofile-agent.cc
git add ./src/profile-generator.cc
git add ./src/v8threads.h
git add ./src/snapshot.h
git add ./src/regexp-macro-assembler-tracer.h
git add ./src/string-stream.h
git add ./src/allocation.cc
git add ./src/compilation-cache.cc
git add ./src/compilation-cache.h
git add ./src/spaces.h
git add ./src/stub-cache.h
git add ./src/virtual-frame-inl.h
git add ./src/debug.h
git add ./src/fast-dtoa.cc
git add ./src/parser.cc
git add ./src/d8-windows.cc
git add ./src/log.h
git add ./src/builtins.h
git add ./src/snapshot-common.cc
git add ./src/diy-fp.cc
git add ./src/compiler.cc
git add ./src/unicode.h
git add ./src/v8natives.js
git add ./src/codegen-inl.h
git add ./src/scanner.cc
git add ./src/regexp-macro-assembler.cc
git add ./src/data-flow.cc
git add ./src/x64/macro-assembler-x64.h
git add ./src/x64/debug-x64.cc
git add ./src/x64/cpu-x64.cc
git add ./src/x64/ic-x64.cc
git add ./src/x64/simulator-x64.cc
git add ./src/x64/disasm-x64.cc
git add ./src/x64/regexp-macro-assembler-x64.h
git add ./src/x64/fast-codegen-x64.cc
git add ./src/x64/regexp-macro-assembler-x64.cc
git add ./src/x64/register-allocator-x64-inl.h
git add ./src/x64/codegen-x64.h
git add ./src/x64/jump-target-x64.cc
git add ./src/x64/register-allocator-x64.cc
git add ./src/x64/virtual-frame-x64.cc
git add ./src/x64/builtins-x64.cc
git add ./src/x64/stub-cache-x64.cc
git add ./src/x64/codegen-x64.cc
git add ./src/x64/assembler-x64.h
git add ./src/x64/full-codegen-x64.cc
git add ./src/x64/macro-assembler-x64.cc
git add ./src/x64/frames-x64.cc
git add ./src/x64/simulator-x64.h
git add ./src/x64/codegen-x64-inl.h
git add ./src/x64/virtual-frame-x64.h
git add ./src/x64/assembler-x64.cc
git add ./src/x64/frames-x64.h
git add ./src/x64/register-allocator-x64.h
git add ./src/x64/assembler-x64-inl.h
git add ./src/objects.h
git add ./src/assembler.h
git add ./src/contexts.cc
git add ./src/d8.js
git add ./src/array.js
git add ./src/interpreter-irregexp.cc
git add ./src/execution.h
git add ./src/messages.js
git add ./src/serialize.h
git add ./src/regexp-macro-assembler-tracer.cc
git add ./src/platform-macos.cc
git add ./src/disasm.h
git add ./src/variables.h
git add ./src/virtual-frame.h
git add ./src/d8-posix.cc
git add ./src/platform-linux.cc
git add ./src/circular-queue.h
git add ./src/natives.h
git add ./src/handles-inl.h
git add ./src/frames-inl.h
git add ./src/v8threads.cc
git add ./src/handles.h
git add ./src/utils.h
git add ./src/utils.cc
git add ./src/arm/codegen-arm.cc
git add ./src/arm/macro-assembler-arm.h
git add ./src/arm/assembler-thumb2.cc
git add ./src/arm/register-allocator-arm.cc
git add ./src/arm/simulator-arm.h
git add ./src/arm/ic-arm.cc
git add ./src/arm/assembler-arm-inl.h
git add ./src/arm/simulator-arm.cc
git add ./src/arm/frames-arm.cc
git add ./src/arm/virtual-frame-arm.cc
git add ./src/arm/register-allocator-arm-inl.h
git add ./src/arm/macro-assembler-arm.cc
git add ./src/arm/register-allocator-arm.h
git add ./src/arm/codegen-arm.h
git add ./src/arm/assembler-arm.h
git add ./src/arm/assembler-arm.cc
git add ./src/arm/debug-arm.cc
git add ./src/arm/regexp-macro-assembler-arm.cc
git add ./src/arm/regexp-macro-assembler-arm.h
git add ./src/arm/constants-arm.h
git add ./src/arm/disasm-arm.cc
git add ./src/arm/jump-target-arm.cc
git add ./src/arm/frames-arm.h
git add ./src/arm/codegen-arm-inl.h
git add ./src/arm/cpu-arm.cc
git add ./src/arm/virtual-frame-arm.h
git add ./src/arm/builtins-arm.cc
git add ./src/arm/assembler-thumb2.h
git add ./src/arm/constants-arm.cc
git add ./src/arm/stub-cache-arm.cc
git add ./src/arm/fast-codegen-arm.cc
git add ./src/arm/assembler-thumb2-inl.h
git add ./src/arm/full-codegen-arm.cc
git add ./src/diy-fp.h
git add ./src/splay-tree.h
git add ./src/platform.h
git add ./src/json.js
git add ./src/global-handles.h
git add ./src/date.js
git add ./src/debug.cc
git add ./src/objects-debug.cc
git add ./src/execution.cc
git add ./src/accessors.h
git add ./src/mirror-debugger.js
git add ./src/arguments.h
git add ./src/char-predicates-inl.h
git add ./src/codegen.h
git add ./src/apinatives.js
git add ./src/variables.cc
git add ./src/ia32/register-allocator-ia32-inl.h
git add ./src/ia32/register-allocator-ia32.h
git add ./src/ia32/ic-ia32.cc
git add ./src/ia32/full-codegen-ia32.cc
git add ./src/ia32/assembler-ia32-inl.h
git add ./src/ia32/codegen-ia32.h
git add ./src/ia32/assembler-ia32.h
git add ./src/ia32/fast-codegen-ia32.cc
git add ./src/ia32/cpu-ia32.cc
git add ./src/ia32/macro-assembler-ia32.cc
git add ./src/ia32/disasm-ia32.cc
git add ./src/ia32/virtual-frame-ia32.cc
git add ./src/ia32/regexp-macro-assembler-ia32.cc
git add ./src/ia32/virtual-frame-ia32.h
git add ./src/ia32/fast-codegen-ia32.h
git add ./src/ia32/regexp-macro-assembler-ia32.h
git add ./src/ia32/codegen-ia32-inl.h
git add ./src/ia32/codegen-ia32.cc
git add ./src/ia32/register-allocator-ia32.cc
git add ./src/ia32/builtins-ia32.cc
git add ./src/ia32/frames-ia32.cc
git add ./src/ia32/jump-target-ia32.cc
git add ./src/ia32/debug-ia32.cc
git add ./src/ia32/stub-cache-ia32.cc
git add ./src/ia32/simulator-ia32.h
git add ./src/ia32/simulator-ia32.cc
git add ./src/ia32/frames-ia32.h
git add ./src/ia32/assembler-ia32.cc
git add ./src/ia32/macro-assembler-ia32.h
git add ./src/zone-inl.h
git add ./src/smart-pointer.h
git add ./src/conversions.h
git add ./src/objects-inl.h
git add ./src/d8-debug.cc
git add ./src/mark-compact.cc
git add ./src/debug-agent.cc
git add ./src/builtins.cc
git add ./src/unicode.cc
git add ./src/jsregexp.cc
git add ./src/contexts.h
git add ./src/property.cc
git add ./src/simulator.h
git add ./src/dateparser.h
git add ./src/full-codegen.cc
git add ./src/register-allocator-inl.h
git add ./src/code.h
git add ./src/zone.cc
git add ./src/dateparser.cc
git add ./src/fast-codegen.cc
git add ./src/dtoa-config.c
git add ./src/regexp-macro-assembler-irregexp-inl.h
git add ./src/frame-element.cc
git add ./src/interpreter-irregexp.h
git add ./src/platform-posix.cc
git add ./src/platform-nullos.cc
git add ./src/regexp-macro-assembler-irregexp.cc
git add ./src/memory.h
git add ./src/factory.cc
git add ./src/frames.h
git add ./src/scopes.cc
git add ./src/list-inl.h
git add ./src/shell.h
git add ./src/heap.h
git add ./src/apiutils.h
git add ./src/mips/virtual-frame-mips.cc
git add ./src/mips/fast-codegen-mips.cc
git add ./src/mips/register-allocator-mips-inl.h
git add ./src/mips/macro-assembler-mips.h
git add ./src/mips/codegen-mips-inl.h
git add ./src/mips/disasm-mips.cc
git add ./src/mips/assembler-mips-inl.h
git add ./src/mips/regexp-macro-assembler-mips.cc
git add ./src/mips/jump-target-mips.cc
git add ./src/mips/regexp-macro-assembler-mips.h
git add ./src/mips/test-interface-mips.h
git add ./src/mips/full-codegen-mips.cc
git add ./src/mips/test-interface-mips.cc
git add ./src/mips/debug-mips.cc
git add ./src/mips/assembler-mips.cc
git add ./src/mips/test-mips.cc
git add ./src/mips/constants-mips.cc
git add ./src/mips/codegen-mips.h
git add ./src/mips/macro-assembler-mips.cc
git add ./src/mips/register-allocator-mips.h
git add ./src/mips/builtins-mips.cc
git add ./src/mips/codegen-mips.cc
git add ./src/mips/virtual-frame-mips.h
git add ./src/mips/readme
git add ./src/mips/stub-cache-mips.cc
git add ./src/mips/constants-mips.h
git add ./src/mips/frames-mips.h
git add ./src/mips/simulator-mips.h
git add ./src/mips/simulator-mips.cc
git add ./src/mips/assembler-mips.h
git add ./src/mips/cpu-mips.cc
git add ./src/mips/frames-mips.cc
git add ./src/mips/ic-mips.cc
git add ./src/mips/register-allocator-mips.cc
git add ./src/code-stubs.h
git add ./src/heap-profiler.cc
git add ./src/bytecodes-irregexp.h
git add ./src/hashmap.h
git add ./src/checks.cc
git add ./src/flag-definitions.h
git add ./src/virtual-frame.cc
git add ./src/mksnapshot.cc
git add ./src/heap.cc
git add ./src/profile-generator-inl.h
git add ./src/regexp-stack.h
git add ./src/oprofile-agent.h
git add ./src/string-stream.cc
git add ./src/conversions.cc
git add ./src/conversions-inl.h
git add ./src/counters.h
git add ./src/factory.h
git add ./src/flags.h
git add ./src/scopeinfo.cc
git add ./src/SConscript
git add ./src/ic.h
git add ./src/prettyprinter.cc
git add ./src/disassembler.cc
git add ./src/rewriter.cc
git add ./src/rewriter.h
git add ./src/platform-solaris.cc
git add ./src/uri.js
git add ./src/assembler.cc
git add ./src/codegen.cc
git add ./src/list.h
git add ./src/circular-queue.cc
git add ./src/v8-counters.h
git add ./src/platform-freebsd.cc
git add ./src/handles.cc
git add ./src/hashmap.cc
git add ./src/version.cc
git add ./src/cpu-profiler.h
git add ./src/d8-debug.h
git add ./src/macro-assembler.h
git add ./src/macros.py
git add ./src/messages.cc
git add ./src/log-utils.cc
git add ./src/api.h
git add ./src/jump-target.h
git add ./src/char-predicates.h
git add ./src/unicode-inl.h
git add ./src/string.js
git add ./src/number-info-inl.h
git add ./src/global-handles.cc
git add ./src/regexp.js
git add ./src/scopes.h
git add ./src/log.cc
git add ./src/token.cc
git add ./src/func-name-inferrer.h
git add ./src/powers-ten.h
git add ./src/disassembler.h
git add ./src/api.cc
git add ./src/spaces.cc
git add ./Android.mksnapshot.mk
git add ./samples/count-hosts.js
git add ./samples/process.cc
git add ./samples/shell.cc
git add ./samples/SConscript
git add ./samples/lineprocessor.cc
git add ./Android.v8shell.mk
git add ./test/message/regress/regress-75.js
git add ./test/message/regress/regress-73.out
git add ./test/message/regress/regress-75.out
git add ./test/message/regress/regress-73.js
git add ./test/message/overwritten-builtins.js
git add ./test/message/try-catch-finally-throw-in-catch.js
git add ./test/message/try-catch-finally-no-message.out
git add ./test/message/simple-throw.js
git add ./test/message/try-catch-finally-throw-in-catch.out
git add ./test/message/try-catch-finally-return-in-finally.js
git add ./test/message/overwritten-builtins.out
git add ./test/message/try-catch-finally-return-in-finally.out
git add ./test/message/try-finally-throw-in-try-and-finally.out
git add ./test/message/try-catch-finally-no-message.js
git add ./test/message/try-catch-finally-throw-in-catch-and-finally.out
git add ./test/message/simple-throw.out
git add ./test/message/try-finally-return-in-finally.js
git add ./test/message/testcfg.py
git add ./test/message/try-finally-throw-in-finally.out
git add ./test/message/try-finally-throw-in-try.js
git add ./test/message/try-finally-throw-in-try-and-finally.js
git add ./test/message/try-finally-return-in-finally.out
git add ./test/message/try-finally-throw-in-try.out
git add ./test/message/try-catch-finally-throw-in-finally.js
git add ./test/message/try-catch-finally-throw-in-catch-and-finally.js
git add ./test/message/message.status
git add ./test/message/try-catch-finally-throw-in-finally.out
git add ./test/message/try-finally-throw-in-finally.js
git add ./test/mozilla/mozilla-shell-emulation.js
git add ./test/mozilla/mozilla.status
git add ./test/mozilla/testcfg.py
git add ./test/mjsunit/to_number_order.js
git add ./test/mjsunit/mirror-string.js
git add ./test/mjsunit/string-lastindexof.js
git add ./test/mjsunit/for-in.js
git add ./test/mjsunit/fun-name.js
git add ./test/mjsunit/top-level-assignments.js
git add ./test/mjsunit/string-search.js
git add ./test/mjsunit/string-split.js
git add ./test/mjsunit/lazy-load.js
git add ./test/mjsunit/arguments-enum.js
git add ./test/mjsunit/regexp-compile.js
git add ./test/mjsunit/debug-continue.js
git add ./test/mjsunit/undeletable-functions.js
git add ./test/mjsunit/delete-vars-from-eval.js
git add ./test/mjsunit/class-of-builtins.js
git add ./test/mjsunit/keyed-storage-extend.js
git add ./test/mjsunit/d8-os.js
git add ./test/mjsunit/try-catch-scopes.js
git add ./test/mjsunit/array-functions-prototype-misc.js
git add ./test/mjsunit/global-vars-with.js
git add ./test/mjsunit/debug-version.js
git add ./test/mjsunit/array-splice.js
git add ./test/mjsunit/regress/regress-892742.js
git add ./test/mjsunit/regress/regress-643.js
git add ./test/mjsunit/regress/regress-1177518.js
git add ./test/mjsunit/regress/regress-124.js
git add ./test/mjsunit/regress/regress-524.js
git add ./test/mjsunit/regress/regress-1134697.js
git add ./test/mjsunit/regress/regress-74.js
git add ./test/mjsunit/regress/regress-682649.js
git add ./test/mjsunit/regress/regress-6-9-regexp.js
git add ./test/mjsunit/regress/regress-992733.js
git add ./test/mjsunit/regress/regress-284.js
git add ./test/mjsunit/regress/regress-193.js
git add ./test/mjsunit/regress/regress-900966.js
git add ./test/mjsunit/regress/regress-496.js
git add ./test/mjsunit/regress/regress-483.js
git add ./test/mjsunit/regress/regress-634.js
git add ./test/mjsunit/regress/regress-674753.js
git add ./test/mjsunit/regress/regress-219.js
git add ./test/mjsunit/regress/regress-990205.js
git add ./test/mjsunit/regress/regress-crbug-18639.js
git add ./test/mjsunit/regress/regress-1493017.js
git add ./test/mjsunit/regress/regress-1199401.js
git add ./test/mjsunit/regress/regress-1102760.js
git add ./test/mjsunit/regress/regress-1201933.js
git add ./test/mjsunit/regress/regress-646.js
git add ./test/mjsunit/regress/regress-1207276.js
git add ./test/mjsunit/regress/regress-1039610.js
git add ./test/mjsunit/regress/regress-545.js
git add ./test/mjsunit/regress/regress-171.js
git add ./test/mjsunit/regress/regress-221.js
git add ./test/mjsunit/regress/regress-87.js
git add ./test/mjsunit/regress/regress-227.js
git add ./test/mjsunit/regress/regress-996542.js
git add ./test/mjsunit/regress/regress-334.js
git add ./test/mjsunit/regress/regress-1030466.js
git add ./test/mjsunit/regress/regress-crbug-3867.js
git add ./test/mjsunit/regress/regress-503.js
git add ./test/mjsunit/regress/regress-260.js
git add ./test/mjsunit/regress/regress-345.js
git add ./test/mjsunit/regress/regress-641.js
git add ./test/mjsunit/regress/regress-267.js
git add ./test/mjsunit/regress/regress-492.js
git add ./test/mjsunit/regress/regress-191.js
git add ./test/mjsunit/regress/regress-1182832.js
git add ./test/mjsunit/regress/regress-326.js
git add ./test/mjsunit/regress/regress-263.js
git add ./test/mjsunit/regress/regress-1254366.js
git add ./test/mjsunit/regress/regress-612.js
git add ./test/mjsunit/regress/regress-396.js
git add ./test/mjsunit/regress/regress-386.js
git add ./test/mjsunit/regress/regress-351.js
git add ./test/mjsunit/regress/regress-244.js
git add ./test/mjsunit/regress/regress-502.js
git add ./test/mjsunit/regress/regress-603.js
git add ./test/mjsunit/regress/regress-900055.js
git add ./test/mjsunit/regress/regress-279.js
git add ./test/mjsunit/regress/regress-186.js
git add ./test/mjsunit/regress/regress-526.js
git add ./test/mjsunit/regress/regress-1919169.js
git add ./test/mjsunit/regress/regress-842017.js
git add ./test/mjsunit/regress/regress-1112051.js
git add ./test/mjsunit/regress/regress-1081309.js
git add ./test/mjsunit/regress/regress-1036894.js
git add ./test/mjsunit/regress/regress-1175390.js
git add ./test/mjsunit/regress/regress-1346700.js
git add ./test/mjsunit/regress/regress-114.js
git add ./test/mjsunit/regress/regress-246.js
git add ./test/mjsunit/regress/regress-806473.js
git add ./test/mjsunit/regress/regress-1200351.js
git add ./test/mjsunit/regress/regress-1177809.js
git add ./test/mjsunit/regress/regress-312.js
git add ./test/mjsunit/regress/regress-515.js
git add ./test/mjsunit/regress/regress-1213575.js
git add ./test/mjsunit/regress/regress-491.js
git add ./test/mjsunit/regress/regress-1341167.js
git add ./test/mjsunit/regress/regress-670147.js
git add ./test/mjsunit/regress/regress-187.js
git add ./test/mjsunit/regress/regress-406.js
git add ./test/mjsunit/regress/regress-1178598.js
git add ./test/mjsunit/regress/regress-1327557.js
git add ./test/mjsunit/regress/regress-475.js
git add ./test/mjsunit/regress/regress-734862.js
git add ./test/mjsunit/regress/regress-2249423.js
git add ./test/mjsunit/regress/regress-1170187.js
git add ./test/mjsunit/regress/regress-737588.js
git add ./test/mjsunit/regress/regress-485.js
git add ./test/mjsunit/regress/regress-233.js
git add ./test/mjsunit/regress/regress-1173979.js
git add ./test/mjsunit/regress/regress-486.js
git add ./test/mjsunit/regress/regress-1199637.js
git add ./test/mjsunit/regress/regress-crbug-37853.js
git add ./test/mjsunit/regress/regress-86.js
git add ./test/mjsunit/regress/regress-r3391.js
git add ./test/mjsunit/regress/regress-254.js
git add ./test/mjsunit/regress/regress-1110164.js
git add ./test/mjsunit/regress/regress-678525.js
git add ./test/mjsunit/regress/regress-116.js
git add ./test/mjsunit/regress/regress-666721.js
git add ./test/mjsunit/regress/regress-662254.js
git add ./test/mjsunit/regress/regress-667061.js
git add ./test/mjsunit/regress/regress-189.js
git add ./test/mjsunit/regress/regress-341.js
git add ./test/mjsunit/regress/regress-580.js
git add ./test/mjsunit/regress/regress-269.js
git add ./test/mjsunit/regress/regress-998565.js
git add ./test/mjsunit/regress/regress-317.js
git add ./test/mjsunit/regress/regress-crbug-3184.js
git add ./test/mjsunit/regress/regress-192.js
git add ./test/mjsunit/regress/regress-874178.js
git add ./test/mjsunit/regress/regress-176.js
git add ./test/mjsunit/regress/regress-490.js
git add ./test/mjsunit/regress/regress-636.js
git add ./test/mjsunit/regress/regress-1066899.js
git add ./test/mjsunit/regress/regress-149.js
git add ./test/mjsunit/regress/regress-265.js
git add ./test/mjsunit/regress/regress-588599.js
git add ./test/mjsunit/regress/regress-286.js
git add ./test/mjsunit/regress/regress-875031.js
git add ./test/mjsunit/regress/regress-799761.js
git add ./test/mjsunit/regress/regress-220.js
git add ./test/mjsunit/regress/regress-137.js
git add ./test/mjsunit/regress/regress-937896.js
git add ./test/mjsunit/regress/regress-225.js
git add ./test/mjsunit/regress/regress-676025.js
git add ./test/mjsunit/regress/regress-416.js
git add ./test/mjsunit/regress/regress-392.js
git add ./test/mjsunit/regress/regress-201.js
git add ./test/mjsunit/regress/regress-925537.js
git add ./test/mjsunit/regress/regress-1114040.js
git add ./test/mjsunit/regress/regress-318.js
git add ./test/mjsunit/regress/regress-69.js
git add ./test/mjsunit/regress/regress-780423.js
git add ./test/mjsunit/regress/regress-540.js
git add ./test/mjsunit/regress/regress-397.js
git add ./test/mjsunit/regress/regress-35.js
git add ./test/mjsunit/regress/regress-294.js
git add ./test/mjsunit/regress/regress-20070207.js
git add ./test/mjsunit/regress/regress-1062422.js
git add ./test/mjsunit/regress/regress-57.js
git add ./test/mjsunit/regress/regress-253.js
git add ./test/mjsunit/regress/regress-1050043.js
git add ./test/mjsunit/regress/regress-1203459.js
git add ./test/mjsunit/regress/regress-399.js
git add ./test/mjsunit/regress/regress-877615.js
git add ./test/mjsunit/regress/regress-349.js
git add ./test/mjsunit/regress/regress-1215653.js
git add ./test/mjsunit/regress/regress-231.js
git add ./test/mjsunit/regress/regress-259.js
git add ./test/mjsunit/regress/regress-1439135.js
git add ./test/mjsunit/regress/regress-155924.js
git add ./test/mjsunit/regress/regress-394.js
git add ./test/mjsunit/regress/regress-91.js
git add ./test/mjsunit/regress/regress-1187524.js
git add ./test/mjsunit/regress/regress-1213516.js
git add ./test/mjsunit/string-add.js
git add ./test/mjsunit/context-variable-assignments.js
git add ./test/mjsunit/delete-global-properties.js
git add ./test/mjsunit/number-limits.js
git add ./test/mjsunit/global-deleted-property-ic.js
git add ./test/mjsunit/deep-recursion.js
git add ./test/mjsunit/third_party/array-splice-webkit.js
git add ./test/mjsunit/third_party/object-keys.js
git add ./test/mjsunit/third_party/array-isarray.js
git add ./test/mjsunit/third_party/regexp-pcre.js
git add ./test/mjsunit/third_party/string-trim.js
git add ./test/mjsunit/mirror-unresolved-function.js
git add ./test/mjsunit/arguments-opt.js
git add ./test/mjsunit/debug-stepin-constructor.js
git add ./test/mjsunit/invalid-lhs.js
git add ./test/mjsunit/array-length.js
git add ./test/mjsunit/string-indexof-2.js
git add ./test/mjsunit/megamorphic-callbacks.js
git add ./test/mjsunit/bugs/bug-941049.js
git add ./test/mjsunit/bugs/618.js
git add ./test/mjsunit/bugs/bug-900066.js
git add ./test/mjsunit/bugs/bug-618.js
git add ./test/mjsunit/bugs/bug-1344252.js
git add ./test/mjsunit/bugs/bug-619.js
git add ./test/mjsunit/bugs/bug-222.js
git add ./test/mjsunit/sparse-array-reverse.js
git add ./test/mjsunit/debug-multiple-breakpoints.js
git add ./test/mjsunit/arguments-call-apply.js
git add ./test/mjsunit/indexed-accessors.js
git add ./test/mjsunit/escape.js
git add ./test/mjsunit/with-leave.js
git add ./test/mjsunit/transcendentals.js
git add ./test/mjsunit/short-circuit-boolean.js
git add ./test/mjsunit/dtoa.js
git add ./test/mjsunit/regexp-multiline.js
git add ./test/mjsunit/number-tostring.js
git add ./test/mjsunit/object-literal.js
git add ./test/mjsunit/array-push.js
git add ./test/mjsunit/regexp-captures.js
git add ./test/mjsunit/if-in-undefined.js
git add ./test/mjsunit/integer-to-string.js
git add ./test/mjsunit/object-get-own-property-names.js
git add ./test/mjsunit/mirror-script.js
git add ./test/mjsunit/do-not-strip-fc.js
git add ./test/mjsunit/nul-characters.js
git add ./test/mjsunit/getter-in-value-prototype.js
git add ./test/mjsunit/debug-evaluate-arguments.js
git add ./test/mjsunit/mirror-boolean.js
git add ./test/mjsunit/in.js
git add ./test/mjsunit/compare-character.js
git add ./test/mjsunit/debug-references.js
git add ./test/mjsunit/dont-enum-array-holes.js
git add ./test/mjsunit/array-shift.js
git add ./test/mjsunit/ascii-regexp-subject.js
git add ./test/mjsunit/string-compare-alignment.js
git add ./test/mjsunit/object-define-property.js
git add ./test/mjsunit/body-not-visible.js
git add ./test/mjsunit/closure.js
git add ./test/mjsunit/abs.js
git add ./test/mjsunit/debug-sourceslice.js
git add ./test/mjsunit/debug-clearbreakpoint.js
git add ./test/mjsunit/try.js
git add ./test/mjsunit/leakcheck.js
git add ./test/mjsunit/unicode-test.js
git add ./test/mjsunit/this-in-callbacks.js
git add ./test/mjsunit/length.js
git add ./test/mjsunit/const-redecl.js
git add ./test/mjsunit/array-functions-prototype.js
git add ./test/mjsunit/debug-event-listener.js
git add ./test/mjsunit/debug-evaluate-locals.js
git add ./test/mjsunit/string-flatten.js
git add ./test/mjsunit/codegen-coverage.js
git add ./test/mjsunit/html-comments.js
git add ./test/mjsunit/no-branch-elimination.js
git add ./test/mjsunit/big-array-literal.js
git add ./test/mjsunit/override-read-only-property.js
git add ./test/mjsunit/math-round.js
git add ./test/mjsunit/fuzz-natives.js
git add ./test/mjsunit/debug-evaluate-bool-constructor.js
git add ./test/mjsunit/debug-ignore-breakpoints.js
git add ./test/mjsunit/array-elements-from-array-prototype.js
git add ./test/mjsunit/delay-syntax-error.js
git add ./test/mjsunit/has-own-property.js
git add ./test/mjsunit/array-length-number-conversion.js
git add ./test/mjsunit/property-load-across-eval.js
git add ./test/mjsunit/math-sqrt.js
git add ./test/mjsunit/property-object-key.js
git add ./test/mjsunit/newline-in-string.js
git add ./test/mjsunit/error-constructors.js
git add ./test/mjsunit/regexp-standalones.js
git add ./test/mjsunit/negate.js
git add ./test/mjsunit/declare-locally.js
git add ./test/mjsunit/array-indexing.js
git add ./test/mjsunit/multiple-return.js
git add ./test/mjsunit/debug-evaluate-with.js
git add ./test/mjsunit/switch.js
git add ./test/mjsunit/math-min-max.js
git add ./test/mjsunit/mjsunit.js
git add ./test/mjsunit/eval-typeof-non-existing.js
git add ./test/mjsunit/string-index.js
git add ./test/mjsunit/div-mod.js
git add ./test/mjsunit/html-string-funcs.js
git add ./test/mjsunit/mirror-object.js
git add ./test/mjsunit/array-reduce.js
git add ./test/mjsunit/array-unshift.js
git add ./test/mjsunit/smi-ops.js
git add ./test/mjsunit/function.js
git add ./test/mjsunit/receiver-in-with-calls.js
git add ./test/mjsunit/large-object-literal.js
git add ./test/mjsunit/debug-conditional-breakpoints.js
git add ./test/mjsunit/string-charat.js
git add ./test/mjsunit/with-value.js
git add ./test/mjsunit/debug-stepin-function-call.js
git add ./test/mjsunit/fuzz-accessors.js
git add ./test/mjsunit/call.js
git add ./test/mjsunit/string-localecompare.js
git add ./test/mjsunit/function-arguments-null.js
git add ./test/mjsunit/array-elements-from-array-prototype-chain.js
git add ./test/mjsunit/debug-backtrace.js
git add ./test/mjsunit/debug-scopes.js
git add ./test/mjsunit/function-property.js
git add ./test/mjsunit/toint32.js
git add ./test/mjsunit/global-ic.js
git add ./test/mjsunit/array-slice.js
git add ./test/mjsunit/with-function-expression.js
git add ./test/mjsunit/regexp-call-as-function.js
git add ./test/mjsunit/date-parse.js
git add ./test/mjsunit/stack-traces.js
git add ./test/mjsunit/function-names.js
git add ./test/mjsunit/execScript-case-insensitive.js
git add ./test/mjsunit/regexp-cache-replace.js
git add ./test/mjsunit/function-prototype.js
git add ./test/mjsunit/typeof.js
git add ./test/mjsunit/dont-reinit-global-var.js
git add ./test/mjsunit/const.js
git add ./test/mjsunit/debug-breakpoints.js
git add ./test/mjsunit/this.js
git add ./test/mjsunit/no-semicolon.js
git add ./test/mjsunit/debug-compile-event.js
git add ./test/mjsunit/regexp-UC16.js
git add ./test/mjsunit/strict-equals.js
git add ./test/mjsunit/arguments-indirect.js
git add ./test/mjsunit/array-sort.js
git add ./test/mjsunit/apply.js
git add ./test/mjsunit/touint32.js
git add ./test/mjsunit/call-non-function-call.js
git add ./test/mjsunit/arguments-lazy.js
git add ./test/mjsunit/array-concat.js
git add ./test/mjsunit/global-const-var-conflicts.js
git add ./test/mjsunit/regexp-capture.js
git add ./test/mjsunit/debug-enable-disable-breakpoints.js
git add ./test/mjsunit/debug-constructed-by.js
git add ./test/mjsunit/sin-cos.js
git add ./test/mjsunit/fun-as-prototype.js
git add ./test/mjsunit/debug-evaluate-recursive.js
git add ./test/mjsunit/mirror-undefined.js
git add ./test/mjsunit/debug-script-breakpoints.js
git add ./test/mjsunit/throw-exception-for-null-access.js
git add ./test/mjsunit/debug-stepnext-do-while.js
git add ./test/mjsunit/instanceof.js
git add ./test/mjsunit/string-replace-gc.js
git add ./test/mjsunit/substr.js
git add ./test/mjsunit/debug-stepin-builtin.js
git add ./test/mjsunit/proto.js
git add ./test/mjsunit/debug-script.js
git add ./test/mjsunit/array-join.js
git add ./test/mjsunit/try-finally-nested.js
git add ./test/mjsunit/extra-arguments.js
git add ./test/mjsunit/setter-on-constructor-prototype.js
git add ./test/mjsunit/regexp-loop-capture.js
git add ./test/mjsunit/string-case.js
git add ./test/mjsunit/json.js
git add ./test/mjsunit/date.js
git add ./test/mjsunit/eval.js
git add ./test/mjsunit/bitwise-operations-undefined.js
git add ./test/mjsunit/no-octal-constants-above-256.js
git add ./test/mjsunit/regexp-string-methods.js
git add ./test/mjsunit/enumeration-order.js
git add ./test/mjsunit/debug-step-stub-callfunction.js
git add ./test/mjsunit/for.js
git add ./test/mjsunit/global-load-from-eval.js
git add ./test/mjsunit/throw-and-catch-function.js
git add ./test/mjsunit/compiler/globals.js
git add ./test/mjsunit/compiler/objectliterals.js
git add ./test/mjsunit/compiler/simple-binary-op.js
git add ./test/mjsunit/compiler/countoperation.js
git add ./test/mjsunit/compiler/short-circuit.js
git add ./test/mjsunit/compiler/unary-add.js
git add ./test/mjsunit/compiler/jsnatives.js
git add ./test/mjsunit/compiler/simple-global-access.js
git add ./test/mjsunit/compiler/function-call.js
git add ./test/mjsunit/compiler/assignment.js
git add ./test/mjsunit/compiler/literals-assignment.js
git add ./test/mjsunit/compiler/property-simple.js
git add ./test/mjsunit/compiler/loops.js
git add ./test/mjsunit/compiler/literals.js
git add ./test/mjsunit/compiler/simple-bailouts.js
git add ./test/mjsunit/compiler/this-property-refs.js
git add ./test/mjsunit/compiler/loopcount.js
git add ./test/mjsunit/compiler/thisfunction.js
git add ./test/mjsunit/debug-mirror-cache.js
git add ./test/mjsunit/regexp-indexof.js
git add ./test/mjsunit/large-object-allocation.js
git add ./test/mjsunit/global-load-from-nested-eval.js
git add ./test/mjsunit/const-eval-init.js
git add ./test/mjsunit/regexp-lookahead.js
git add ./test/mjsunit/arguments-read-and-assignment.js
git add ./test/mjsunit/tools/tickprocessor.js
git add ./test/mjsunit/tools/consarray.js
git add ./test/mjsunit/tools/tickprocessor-test-func-info.log
git add ./test/mjsunit/tools/tickprocessor-test.default
git add ./test/mjsunit/tools/profile.js
git add ./test/mjsunit/tools/csvparser.js
git add ./test/mjsunit/tools/tickprocessor-test.ignore-unknown
git add ./test/mjsunit/tools/codemap.js
git add ./test/mjsunit/tools/tickprocessor-test.separate-ic
git add ./test/mjsunit/tools/profile_view.js
git add ./test/mjsunit/tools/tickprocessor-test.gc-state
git add ./test/mjsunit/tools/splaytree.js
git add ./test/mjsunit/tools/tickprocessor-test.log
git add ./test/mjsunit/tools/tickprocessor-test.func-info
git add ./test/mjsunit/tools/logreader.js
git add ./test/mjsunit/string-indexof-1.js
git add ./test/mjsunit/to-precision.js
git add ./test/mjsunit/str-to-num.js
git add ./test/mjsunit/string-split-cache.js
git add ./test/mjsunit/constant-folding.js
git add ./test/mjsunit/debug-liveedit-patch-positions-replace.js
git add ./test/mjsunit/debug-sourceinfo.js
git add ./test/mjsunit/unicode-case-overoptimization.js
git add ./test/mjsunit/greedy.js
git add ./test/mjsunit/debug-backtrace-text.js
git add ./test/mjsunit/api-call-after-bypassed-exception.js
git add ./test/mjsunit/mirror-array.js
git add ./test/mjsunit/mirror-regexp.js
git add ./test/mjsunit/arguments-apply.js
git add ./test/mjsunit/object-define-properties.js
git add ./test/mjsunit/global-vars-eval.js
git add ./test/mjsunit/function-caller.js
git add ./test/mjsunit/debug-stepin-call-function-stub.js
git add ./test/mjsunit/smi-negative-zero.js
git add ./test/mjsunit/debug-suspend.js
git add ./test/mjsunit/number-string-index-call.js
git add ./test/mjsunit/regexp-static.js
git add ./test/mjsunit/number-tostring-small.js
git add ./test/mjsunit/cyclic-array-to-string.js
git add ./test/mjsunit/testcfg.py
git add ./test/mjsunit/debug-liveedit-check-stack.js
git add ./test/mjsunit/invalid-source-element.js
git add ./test/mjsunit/string-replace.js
git add ./test/mjsunit/debug-stepout-recursive-function.js
git add ./test/mjsunit/stress-array-push.js
git add ./test/mjsunit/function-source.js
git add ./test/mjsunit/debug-stepout-to-builtin.js
git add ./test/mjsunit/char-escape.js
git add ./test/mjsunit/cyrillic.js
git add ./test/mjsunit/tobool.js
git add ./test/mjsunit/string-charcodeat.js
git add ./test/mjsunit/debug-compile-event-newfunction.js
git add ./test/mjsunit/delete.js
git add ./test/mjsunit/simple-constructor.js
git add ./test/mjsunit/scanner.js
git add ./test/mjsunit/debug-evaluate.js
git add ./test/mjsunit/with-parameter-access.js
git add ./test/mjsunit/big-object-literal.js
git add ./test/mjsunit/compare-nan.js
git add ./test/mjsunit/delete-in-eval.js
git add ./test/mjsunit/debug-handle.js
git add ./test/mjsunit/get-prototype-of.js
git add ./test/mjsunit/for-in-null-or-undefined.js
git add ./test/mjsunit/debug-setbreakpoint.js
git add ./test/mjsunit/global-deleted-property-keyed.js
git add ./test/mjsunit/object-create.js
git add ./test/mjsunit/object-literal-gc.js
git add ./test/mjsunit/debug-liveedit-2.js
git add ./test/mjsunit/array-elements-from-object-prototype.js
git add ./test/mjsunit/with-prototype.js
git add ./test/mjsunit/mirror-error.js
git add ./test/mjsunit/non-ascii-replace.js
git add ./test/mjsunit/binary-operation-overwrite.js
git add ./test/mjsunit/debug-step.js
git add ./test/mjsunit/call-non-function.js
git add ./test/mjsunit/array-iteration.js
git add ./test/mjsunit/debug-constructor.js
git add ./test/mjsunit/local-load-from-eval.js
git add ./test/mjsunit/keyed-ic.js
git add ./test/mjsunit/double-equals.js
git add ./test/mjsunit/mjsunit.status
git add ./test/mjsunit/var.js
git add ./test/mjsunit/getter-in-prototype.js
git add ./test/mjsunit/debug-clearbreakpointgroup.js
git add ./test/mjsunit/unusual-constructor.js
git add ./test/mjsunit/uri.js
git add ./test/mjsunit/for-in-special-cases.js
git add ./test/mjsunit/mul-exhaustive.js
git add ./test/mjsunit/const-declaration.js
git add ./test/mjsunit/debug-changebreakpoint.js
git add ./test/mjsunit/value-callic-prototype-change.js
git add ./test/mjsunit/unicode-string-to-number.js
git add ./test/mjsunit/mirror-date.js
git add ./test/mjsunit/new.js
git add ./test/mjsunit/debug-liveedit-1.js
git add ./test/mjsunit/try-catch-extension-object.js
git add ./test/mjsunit/array-constructor.js
git add ./test/mjsunit/debug-liveedit-patch-positions.js
git add ./test/mjsunit/sparse-array.js
git add ./test/mjsunit/delete-in-with.js
git add ./test/mjsunit/get-own-property-descriptor.js
git add ./test/mjsunit/debug-referenced-by.js
git add ./test/mjsunit/value-wrapper.js
git add ./test/mjsunit/parse-int-float.js
git add ./test/mjsunit/extra-commas.js
git add ./test/mjsunit/arguments.js
git add ./test/mjsunit/mirror-function.js
git add ./test/mjsunit/obj-construct.js
git add ./test/mjsunit/string-match.js
git add ./test/mjsunit/array-pop.js
git add ./test/mjsunit/debug-stepin-accessor.js
git add ./test/mjsunit/eval-enclosing-function-name.js
git add ./test/mjsunit/regexp.js
git add ./test/mjsunit/negate-zero.js
git add ./test/mjsunit/prototype.js
git add ./test/mjsunit/mirror-number.js
git add ./test/mjsunit/debug-scripts-request.js
git add ./test/mjsunit/global-load-from-eval-in-with.js
git add ./test/mjsunit/mirror-null.js
git add ./test/mjsunit/bit-not.js
git add ./test/mjsunit/regexp-multiline-stack-trace.js
git add ./test/es5conform/harness-adapt.js
git add ./test/es5conform/README
git add ./test/es5conform/testcfg.py
git add ./test/es5conform/es5conform.status
git add ./test/cctest/test-spaces.cc
git add ./test/cctest/test-hashmap.cc
git add ./test/cctest/test-assembler-arm.cc
git add ./test/cctest/test-heap-profiler.cc
git add ./test/cctest/test-alloc.cc
git add ./test/cctest/test-assembler-x64.cc
git add ./test/cctest/test-log-utils.cc
git add ./test/cctest/test-parsing.cc
git add ./test/cctest/test-thread-termination.cc
git add ./test/cctest/test-regexp.cc
git add ./test/cctest/test-log.cc
git add ./test/cctest/test-compiler.cc
git add ./test/cctest/test-decls.cc
git add ./test/cctest/test-debug.cc
git add ./test/cctest/test-assembler-ia32.cc
git add ./test/cctest/test-disasm-ia32.cc
git add ./test/cctest/test-platform-linux.cc
git add ./test/cctest/gay-shortest.cc
git add ./test/cctest/test-ast.cc
git add ./test/cctest/test-cpu-profiler.cc
git add ./test/cctest/test-mips.cc
git add ./test/cctest/test-serialize.cc
git add ./test/cctest/test-accessors.cc
git add ./test/cctest/cctest.cc
git add ./test/cctest/test-utils.cc
git add ./test/cctest/test-disasm-arm.cc
git add ./test/cctest/test-platform-macos.cc
git add ./test/cctest/test-sockets.cc
git add ./test/cctest/test-lock.cc
git add ./test/cctest/test-diy-fp.cc
git add ./test/cctest/test-macro-assembler-x64.cc
git add ./test/cctest/gay-shortest.h
git add ./test/cctest/test-conversions.cc
git add ./test/cctest/test-list.cc
git add ./test/cctest/cctest.h
git add ./test/cctest/test-api.cc
git add ./test/cctest/test-double.cc
git add ./test/cctest/test-mark-compact.cc
git add ./test/cctest/test-dataflow.cc
git add ./test/cctest/test-platform-win32.cc
git add ./test/cctest/testcfg.py
git add ./test/cctest/test-assembler-mips.cc
git add ./test/cctest/test-platform-nullos.cc
git add ./test/cctest/test-flags.cc
git add ./test/cctest/test-circular-queue.cc
git add ./test/cctest/test-func-name-inference.cc
git add ./test/cctest/test-threads.cc
git add ./test/cctest/SConscript
git add ./test/cctest/test-strings.cc
git add ./test/cctest/test-log-stack-tracer.cc
git add ./test/cctest/test-profile-generator.cc
git add ./test/cctest/test-heap.cc
git add ./test/cctest/cctest.status
git add ./test/cctest/test-version.cc
git add ./test/cctest/test-fast-dtoa.cc
git add ./test/sputnik/sputnik.status
git add ./test/sputnik/README
git add ./test/sputnik/testcfg.py
git add ./Android.v8common.mk
git add ./ChangeLog
git add ./AUTHORS
git add ./Android.libv8.mk
git add ./LICENSE
git add ./tools/js2c.py
git add ./tools/process-heap-prof.py
git add ./tools/mac-tick-processor
git add ./tools/tickprocessor.js
git add ./tools/consarray.js
git add ./tools/test.py
git add ./tools/tickprocessor-driver.js
git add ./tools/visual_studio/v8_shell_sample_arm.vcproj
git add ./tools/visual_studio/v8_mksnapshot_x64.vcproj
git add ./tools/visual_studio/release.vsprops
git add ./tools/visual_studio/v8_process_sample_arm.vcproj
git add ./tools/visual_studio/ia32.vsprops
git add ./tools/visual_studio/v8_process_sample.vcproj
git add ./tools/visual_studio/v8_cctest.vcproj
git add ./tools/visual_studio/v8_snapshot.vcproj
git add ./tools/visual_studio/v8_snapshot_cc_x64.vcproj
git add ./tools/visual_studio/v8_base.vcproj
git add ./tools/visual_studio/x64.vsprops
git add ./tools/visual_studio/v8_snapshot_cc.vcproj
git add ./tools/visual_studio/d8js2c.cmd
git add ./tools/visual_studio/common.vsprops
git add ./tools/visual_studio/v8_cctest_arm.vcproj
git add ./tools/visual_studio/v8_x64.vcproj
git add ./tools/visual_studio/v8_arm.sln
git add ./tools/visual_studio/v8_x64.sln
git add ./tools/visual_studio/d8.vcproj
git add ./tools/visual_studio/d8_x64.vcproj
git add ./tools/visual_studio/v8_shell_sample_x64.vcproj
git add ./tools/visual_studio/v8_base_x64.vcproj
git add ./tools/visual_studio/debug.vsprops
git add ./tools/visual_studio/v8_arm.vcproj
git add ./tools/visual_studio/v8_mksnapshot.vcproj
git add ./tools/visual_studio/v8_process_sample_x64.vcproj
git add ./tools/visual_studio/v8_cctest_x64.vcproj
git add ./tools/visual_studio/README.txt
git add ./tools/visual_studio/d8_arm.vcproj
git add ./tools/visual_studio/js2c.cmd
git add ./tools/visual_studio/v8.vcproj
git add ./tools/visual_studio/v8_snapshot_x64.vcproj
git add ./tools/visual_studio/v8_base_arm.vcproj
git add ./tools/visual_studio/arm.vsprops
git add ./tools/visual_studio/v8.sln
git add ./tools/visual_studio/v8_shell_sample.vcproj
git add ./tools/windows-tick-processor.bat
git add ./tools/generate-ten-powers.scm
git add ./tools/tickprocessor.py
git add ./tools/profile.js
git add ./tools/csvparser.js
git add ./tools/run-valgrind.py
git add ./tools/jsmin.py
git add ./tools/presubmit.py
git add ./tools/codemap.js
git add ./tools/stats-viewer.py
git add ./tools/windows-tick-processor.py
git add ./tools/profile_view.js
git add ./tools/v8.xcodeproj/project.pbxproj
git add ./tools/mac-nm
git add ./tools/linux-tick-processor
git add ./tools/splaytree.py
git add ./tools/utils.py
git add ./tools/splaytree.js
git add ./tools/oprofile/shutdown
git add ./tools/oprofile/run
git add ./tools/oprofile/common
git add ./tools/oprofile/reset
git add ./tools/oprofile/annotate
git add ./tools/oprofile/dump
git add ./tools/oprofile/report
git add ./tools/oprofile/start
git add ./tools/gyp/v8.gyp
git add ./tools/logreader.js
git add ./tools/linux-tick-processor.py
git add ./CleanSpec.mk
git add ./Android.mk
git add ./SConstruct
git add ./benchmarks/earley-boyer.js
git add ./benchmarks/crypto.js
git add ./benchmarks/v8-logo.png
git add ./benchmarks/base.js
git add ./benchmarks/run.html
git add ./benchmarks/deltablue.js
git add ./benchmarks/raytrace.js
git add ./benchmarks/run.js
git add ./benchmarks/style.css
git add ./benchmarks/splay.js
git add ./benchmarks/README.txt
git add ./benchmarks/revisions.html
git add ./benchmarks/regexp.js
git add ./benchmarks/richards.js
